services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: tennis_app
      POSTGRES_USER: tennis_user
      POSTGRES_PASSWORD: tennis_password
    ports:
      - "15432:5432"  # Внешний порт 15432 вместо 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tennis_user -d tennis_app"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tennis-network

  # Основное приложение
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # База данных (внутренний порт остается 5432)
      DATABASE_URL: postgresql://tennis_user:tennis_password@postgres:5432/tennis_app
      
      # JWT
      JWT_SECRET: tennis_super_secret_key_2024_development
      JWT_EXPIRES_IN: 24h
      
      # Приложение
      NODE_ENV: development
      PORT: 3000  # Внутренний порт
      
      # Telegram Bot
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-your_telegram_bot_token_here}
      
      # URLs (используем внешний порт)
      API_BASE_URL: http://localhost:13000
      FRONTEND_URL: http://localhost:13000
      
      # Файлы
      UPLOAD_PATH: ./uploads
      MAX_FILE_SIZE: 5242880
      
      # Логирование
      LOG_LEVEL: debug
      
    ports:
      - "13000:3000"  # Внешний порт 13000 вместо 3000
      - "19229:9229"  # Порт для отладки 19229 вместо 9229
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - tennis-network
    command: ["npm", "run", "start:debug"]

  # Redis для кеширования (опционально)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "16379:6379"  # Внешний порт 16379 вместо 6379
    volumes:
      - redis_data:/data
    networks:
      - tennis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  tennis-network:
    driver: bridge