export enum TournamentType {
  SINGLE_ELIMINATION = 'SINGLE_ELIMINATION',
  GROUPS_PLAYOFF = 'GROUPS_PLAYOFF',
  LEAGUE = 'LEAGUE',
  BLITZ = 'BLITZ'
}

export enum TournamentStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED'
}

export enum MatchStatus {
  SCHEDULED = 'SCHEDULED',
  FINISHED = 'FINISHED',
  CANCELLED = 'CANCELLED'
}